### ISSUE TITLE
Support version 2.1.0 in sonarqube.com ?

### ISSUE THREAD

**Issue by vhamon** [QualInsight/qualinsight-plugins-sonarqube-badges#50]
Hello, 
Nice badges ^^ 
I personnaly use sonarqube.com directly from travis-ci.
According to sonarqube's plugin version matrix, sonarQube only support your plugin up to version 2.0.1:/ 
http://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix
Is it planned soon ?

It would be awesome^^

**Comment by pawlakm** [comment]
Hi, 

Thanks for your feedback (and sorry for the late reply.)

In fact, due to many reasons, I had no time to work on my side projects for a while. As a result, 2.1.0 hasn't been released yet that's why the matrix doesn't shows it. But this will change soon.

I'll build a 2.1.0-RC this WE and hope to have it released next week. Then I'll have to ask SQ people to install the new version of the plugin on SQ.com. 

Unfortunately I have no direct impact on this last part of the process. I can only ask you to participate in the RC review process then "thumb up" my upgrade request once the plugin is released.

Best Regards,

Michel

**Comment by pawlakm** [comment]
Hi,

For your information, I released SVG Badges 2.1.0-RC1 and I'm [waiting for users feedback](https://groups.google.com/forum/#!topic/sonarqube/lmiATC-BAac).

Michel

**Comment by vhamon** [comment]
Hi, thank you very much. I will glance at it. That's okay, we all have many things to do ^^

**Comment by pawlakm** [comment]
The plugin has been released (version 3.0.0) and SonarQube's plugin version matrix has been updated.

**Comment by vhamon** [comment]
Ok thanks a lot. I guess sonarqube.com index will be updated soon. Because it is still 2.0.1 version in it : 
https://sonarqube.com/deploy/plugins/index.txt : 

> status,false,qualinsight-sonarqube-badges-2.0.1.jar|436ba7eca3d739e15bc2a4aac141a752

**Comment by pawlakm** [comment]
@vhamon The plugin has been upgraded on SonarQube.com. New badges and options are now available (you can have a look at the `technical debt ratio` badge added to SVG Badges README.md file)

**Comment by vhamon** [comment]
Tanks a lot :) :+1:
