### ISSUE TITLE
it_coverage metrics showing N/A

### ISSUE THREAD

**Issue by vhamon** [QualInsight/qualinsight-plugins-sonarqube-badges#68]
It does not works since some time, but sorry I can't tell exactly since when it does not work. 

As you can see in my README, it_coverage shows N/A instead of X% : 
https://github.com/armadito/armadito-glpi/blob/DEV/README.md

**Comment by pawlakm** [comment]
Hi, 

This is unfortunately the expected behaviour since SonarQube 6.2. Indeed in 6.2 they removed the it_coverage and overall_coverage metrics. As the metric is not computed anymore, it cannot be retrieved by the Badges plugin, hence the ``N/A``.

For more information please check their JIRA: https://jira.sonarsource.com/browse/MMF-345

Cheers,

Michel

**Comment by pawlakm** [comment]
By the way I closed the issue, because your badge is pointing to the sonarqube.com instance and I know for sure that the metric removal is the root cause of your problem).

You should use the ``coverage`` metric instead. I'll update the wiki page this week end in order to indicate which SQ version is required to display the corresponding badge.

**Comment by vhamon** [comment]
Thanks, Okay, that's fine. I will use coverage metrics instead :)

**Comment by pawlakm** [comment]
wiki updated
